services:
  db:
    image: postgres:15
    container_name: boilerplate_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    ports:
      - "5433:5432"  # ← Port externe 5433, interne 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: